### ISSUE TITLE
ValueError: Checkpoint does not exist

### ISSUE THREAD

**Issue by tianyumyum** [Spico197/CatalogExtraction#2]
Traceback (most recent call last):
  File "/home/2023/CatalogExtraction/examples/doc_tree_construction/train/run.py", line 48, in <module>
    main()
  File "/home/2023/CatalogExtraction/examples/doc_tree_construction/train/run.py", line 29, in main
    task.load_best_ckpt()
  File "/home/2023/miniconda3/envs/doctreeto/lib/python3.8/site-packages/rex/tasks/base_task.py", line 131, in load_best_ckpt
    self.load(ckpt_filepath, load_model=True, load_optimizer=load_optimizer)
  File "/home/2023/miniconda3/envs/doctreeto/lib/python3.8/site-packages/rex/tasks/base_task.py", line 78, in load
    raise ValueError("Checkpoint does not exist, {}".format(path))
ValueError: Checkpoint does not exist, paper_outputs/transducer_plm4w_lrscheduling_-1_DomainMix_127/ckpt/TransducerWithBert.best.pth

  File "/home/2023/CatalogExtraction/examples/doc_tree_construction/train/run.py", line 27, in main
    task.train()
    │    └ <function TransducerDocTreeConstructionTask.train at 0x7fea4f5a9ee0>
    └ <doctree.tasks.transducer_task.TransducerDocTreeConstructionTask object at 0x7feba5741f70>

> File "/home/2023/miniconda3/envs/doctreeto/lib/python3.8/site-packages/rex/utils/wrapper.py", line 21, in try_func
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<doctree.tasks.transducer_task.TransducerDocTreeConstructionTask object at 0x7feba5741f70>,)
           └ <function TransducerDocTreeConstructionTask.train at 0x7feab18950d0>

  File "/home/2023/CatalogExtraction/doctree/tasks/transducer_task.py", line 144, in train
    dev_select_measure = dev_measures["hierarchy"]["overall"]["f1"]
                         └ {'action': {'micro': {'p': 0.9770918947276384, 'r': 0.9770918947276384, 'f1': 0.9770918947276384, 'tp': 11175, 'fp': 262, 'fn...

KeyError: 'overall'
2023-07-03 10:23:13.180 | INFO     | rex.tasks.base_task:load_best_ckpt:130 - Loading model from: paper_outputs/transducer_plm4w_lrscheduling_-1_DomainMix_17/ckpt/TransducerWithBert.best.pth

你好～请问我是缺失了哪一环节吗，我新建了一个文件夹paper_outputs用来存储output，但是发生了报错，尤其提示是在overall的部分。

**Comment by tianyumyum** [comment]
请问这和rex库有关系吗

**Comment by Spico197** [comment]
嗨您好，现在这里报了两个错误，需要逐一排查一下。
- 首先是`paper_outputs/transducer_plm4w_lrscheduling_-1_DomainMix_127/ckpt/TransducerWithBert.best.pth`这个文件是否存在？
- 如果上述文件存在的话，在模型进行评价时，[这里](https://github.com/Spico197/CatalogExtraction/blob/114c37144ddbf660f75a3c32529f33c2ac8bb2ab/doctree/tasks/transducer_task.py#L505)是否运行正常？程序的逻辑是从 `dev_measures` 中选择hierarchy下的overall结果作为best metric的选择标准 `{"action": ..., "hierarchy": {"overall": {...}}}`

**Comment by Spico197** [comment]
`paper_outputs/transducer_plm4w_lrscheduling_-1_DomainMix_127`目录中应该有一个完整的log文件，方便提供一下吗？

**Comment by tianyumyum** [comment]
> 嗨您好，现在这里报了两个错误，需要逐一排查一下。
> 
> * 首先是`paper_outputs/transducer_plm4w_lrscheduling_-1_DomainMix_127/ckpt/TransducerWithBert.best.pth`这个文件是否存在？
> * 如果上述文件存在的话，在模型进行评价时，[这里](https://github.com/Spico197/CatalogExtraction/blob/114c37144ddbf660f75a3c32529f33c2ac8bb2ab/doctree/tasks/transducer_task.py#L505)是否运行正常？程序的逻辑是从 `dev_measures` 中选择hierarchy下的overall结果作为best metric的选择标准 `{"action": ..., "hierarchy": {"overall": {...}}}`

你好我重新clone了仓库，也重新创建了环境，现在没有问题了，怀疑是之前skip_train设置为false，没有改回来，谢谢！
